// The one cookie reader (spec 14 §2.8): yt-dlp exports the browser's jar to
// a temp file, the small clients read what they need and the jar is gone.
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import { cookieHeader, exportCookieJar, parseNetscapeJar, siteRows, writeJar } from '../src/music/sources/cookies.ts'

// A Netscape jar as yt-dlp writes it, values redacted.
const JAR = [
  '# Netscape HTTP Cookie File',
  '# This file is generated by yt-dlp.  Do not edit.',
  '',
  '.music.163.com\tTRUE\t/\tFALSE\t1790000000\tMUSIC_U\t<redacted-music-u>',
  '.music.163.com\tTRUE\t/\tFALSE\t1790000000\t__csrf\t<redacted-csrf>',
  '#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>',
  '.bilibili.com\tTRUE\t/\tFALSE\t1790000000\tDedeUserID\t42',
  '.youtube.com\tTRUE\t/\tTRUE\t1790000000\tSID\t<redacted-sid>',
  'malformed line without tabs',
  '',
].join('\n')

describe('parseNetscapeJar', () => {
  it('reads name, value and domain, HttpOnly rows included, and skips what does not parse', () => {
    const rows = parseNetscapeJar(JAR)
    expect(rows).toHaveLength(5)
    expect(rows[2]).toMatchObject({ domain: '.bilibili.com', name: 'SESSDATA', value: '<redacted-sessdata>' })
    // The line itself rides along, so a jar can be written back for yt-dlp.
    expect(rows[2]!.line).toBe('#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>')
  })

  it('builds a Cookie header for one site and nothing else', () => {
    const rows = parseNetscapeJar(JAR)
    expect(cookieHeader(rows, 'bilibili.com')).toBe('SESSDATA=<redacted-sessdata>; DedeUserID=42')
    expect(cookieHeader(rows, 'music.163.com')).toBe('MUSIC_U=<redacted-music-u>; __csrf=<redacted-csrf>')
    expect(cookieHeader(rows, 'example.com')).toBe('')
  })
})

describe('siteRows + writeJar', () => {
  it('keeps one site\'s rows only, and writes them back as a jar yt-dlp can load, owner-only, gone on release', () => {
    const rows = siteRows(parseNetscapeJar(JAR), 'bilibili.com')
    expect(rows.map((r) => r.name)).toEqual(['SESSDATA', 'DedeUserID'])
    const lease = writeJar(rows)
    expect(lease.args).toEqual(['--cookies', lease.path])
    const text = readFileSync(lease.path, 'utf-8')
    expect(text.startsWith('# Netscape HTTP Cookie File')).toBe(true)
    expect(text).toContain('#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>')
    expect(text).not.toContain('MUSIC_U')
    expect(statSync(lease.path).mode & 0o777).toBe(0o600)
    lease.release()
    expect(existsSync(lease.path)).toBe(false)
  })
})

describe('exportCookieJar', () => {
  it('asks yt-dlp for the browser store, reads the jar it wrote, and deletes it', async () => {
    const calls: string[][] = []
    const jar = await exportCookieJar({ browser: 'brave', profile: 'Profile 1' }, async (args) => {
      calls.push(args)
      const path = args[args.indexOf('--cookies') + 1]!
      writeFileSync(path, JAR)
      return ''
    })
    expect(calls[0]!.slice(0, 2)).toEqual(['--cookies-from-browser', 'brave:Profile 1'])
    expect(calls[0]).toContain('--cookies')
    expect(calls[0]).toContain('--simulate')
    expect(jar).toHaveLength(5)
    const path = calls[0]![calls[0]!.indexOf('--cookies') + 1]!
    expect(existsSync(path)).toBe(false)
  })

  it('a runner that fails without writing a jar yields no cookies, and leaves nothing behind', async () => {
    let path = ''
    const jar = await exportCookieJar({ browser: 'firefox' }, async (args) => {
      path = args[args.indexOf('--cookies') + 1]!
      throw new Error('could not find firefox cookies database')
    })
    expect(jar).toEqual([])
    expect(existsSync(path)).toBe(false)
  })
})
