// The one cookie reader (spec 14 §2.8): yt-dlp exports the browser's jar to
// a temp file, the small clients read what they need and the jar is gone.
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import { COOKIE_TTL_MS, CookieJars } from '../src/music/sources/build.ts'
import { cookieHeader, exportCookieJar, parseNetscapeJar, siteRows, writeJar } from '../src/music/sources/cookies.ts'
import type { YtDlpRunner } from '../src/music/music.ts'

// A Netscape jar as yt-dlp writes it, values redacted.
const JAR = [
  '# Netscape HTTP Cookie File',
  '# This file is generated by yt-dlp.  Do not edit.',
  '',
  '.music.163.com\tTRUE\t/\tFALSE\t1790000000\tMUSIC_U\t<redacted-music-u>',
  '.music.163.com\tTRUE\t/\tFALSE\t1790000000\t__csrf\t<redacted-csrf>',
  '#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>',
  '.bilibili.com\tTRUE\t/\tFALSE\t1790000000\tDedeUserID\t42',
  '.youtube.com\tTRUE\t/\tTRUE\t1790000000\tSID\t<redacted-sid>',
  'malformed line without tabs',
  '',
].join('\n')

describe('parseNetscapeJar', () => {
  it('reads name, value and domain, HttpOnly rows included, and skips what does not parse', () => {
    const rows = parseNetscapeJar(JAR)
    expect(rows).toHaveLength(5)
    expect(rows[2]).toMatchObject({ domain: '.bilibili.com', name: 'SESSDATA', value: '<redacted-sessdata>' })
    // The line itself rides along, so a jar can be written back for yt-dlp.
    expect(rows[2]!.line).toBe('#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>')
  })

  it('builds a Cookie header for one site and nothing else', () => {
    const rows = parseNetscapeJar(JAR)
    expect(cookieHeader(rows, 'bilibili.com')).toBe('SESSDATA=<redacted-sessdata>; DedeUserID=42')
    expect(cookieHeader(rows, 'music.163.com')).toBe('MUSIC_U=<redacted-music-u>; __csrf=<redacted-csrf>')
    expect(cookieHeader(rows, 'example.com')).toBe('')
  })
})

describe('siteRows + writeJar', () => {
  it('keeps one site\'s rows only, and writes them back as a jar yt-dlp can load, owner-only, gone on release', () => {
    const rows = siteRows(parseNetscapeJar(JAR), 'bilibili.com')
    expect(rows.map((r) => r.name)).toEqual(['SESSDATA', 'DedeUserID'])
    const lease = writeJar(rows)
    expect(lease.args).toEqual(['--cookies', lease.path])
    const text = readFileSync(lease.path, 'utf-8')
    expect(text.startsWith('# Netscape HTTP Cookie File')).toBe(true)
    expect(text).toContain('#HttpOnly_.bilibili.com\tTRUE\t/\tTRUE\t1790000000\tSESSDATA\t<redacted-sessdata>')
    expect(text).not.toContain('MUSIC_U')
    expect(statSync(lease.path).mode & 0o777).toBe(0o600)
    lease.release()
    expect(existsSync(lease.path)).toBe(false)
  })
})

describe('exportCookieJar', () => {
  it('asks yt-dlp for the browser store, reads the jar it wrote, and deletes it', async () => {
    const calls: string[][] = []
    const jar = await exportCookieJar({ browser: 'brave', profile: 'Profile 1' }, async (args) => {
      calls.push(args)
      const path = args[args.indexOf('--cookies') + 1]!
      writeFileSync(path, JAR)
      return ''
    })
    expect(calls[0]!.slice(0, 2)).toEqual(['--cookies-from-browser', 'brave:Profile 1'])
    expect(calls[0]).toContain('--cookies')
    expect(calls[0]).toContain('--simulate')
    expect(jar).toHaveLength(5)
    const path = calls[0]![calls[0]!.indexOf('--cookies') + 1]!
    expect(existsSync(path)).toBe(false)
  })

  it('a runner that fails without writing a jar yields no cookies, and leaves nothing behind', async () => {
    let path = ''
    const jar = await exportCookieJar({ browser: 'firefox' }, async (args) => {
      path = args[args.indexOf('--cookies') + 1]!
      throw new Error('could not find firefox cookies database')
    }).catch((err: unknown) => err)
    expect(jar).toMatchObject({ reason: 'no-browser' })
    expect(existsSync(path)).toBe(false)
  })

  // Five different failures used to arrive as one empty jar, and the flow
  // read every one of them as "you are not signed in" — which sent a Safari
  // user to sign in again forever. yt-dlp says which it is; keep its words.
  it('tells a missing browser, a refused cookie store and a missing yt-dlp apart', async () => {
    const thrown = async (message: string, extra: Record<string, unknown> = {}): Promise<unknown> =>
      exportCookieJar({ browser: 'chrome' }, async () => {
        throw Object.assign(new Error(message), extra)
      }).catch((err: unknown) => err)

    expect(await thrown('ERROR: could not find chrome cookies database in \'/Users/x/Library\'')).toMatchObject({
      source: 'chrome',
      reason: 'no-browser',
    })
    expect(await thrown('ERROR: [Errno 1] Operation not permitted: \'/Users/x/Library/Containers/com.apple.Safari\'')).toMatchObject({
      reason: 'no-permission',
    })
    expect(await thrown('spawn yt-dlp ENOENT', { code: 'ENOENT' })).toMatchObject({ reason: 'no-ytdlp' })
    // The detail carries yt-dlp's own words, so a listener can be told what
    // actually went wrong rather than a guess.
    const err = await thrown('ERROR: [Errno 1] Operation not permitted: \'/x\'')
    expect(String((err as { detail: string }).detail)).toContain('Operation not permitted')
  })

  it('an export that worked but holds no row for the site is not a failure — it is a missing login', async () => {
    const rows = await exportCookieJar({ browser: 'chrome' }, async (args) => {
      writeFileSync(args[args.indexOf('--cookies') + 1]!, JAR)
      return ''
    })
    expect(cookieHeader(rows, 'example.invalid')).toBe('')
  })
})

// spec 14 §2.8 (review round): one export per browser per site per TTL — an
// export that found nothing is never cached (the listener signs in and
// retries at once), and concurrent readers share the one in-flight export
// instead of spawning yt-dlp three times.
describe('CookieJars', () => {
  it('coalesces concurrent exports, caches a hit, never caches an empty one, and forgets on demand', async () => {
    let exports = 0
    let jar = JAR
    const run: YtDlpRunner = async (args) => {
      exports++
      await new Promise((r) => setTimeout(r, 5))
      writeFileSync(args[args.indexOf('--cookies') + 1]!, jar)
      return ''
    }
    let clock = 0
    const jars = new CookieJars(run, () => clock)
    const pick = { browser: 'chrome' as const }
    const three = await Promise.all([
      jars.header(pick, 'bilibili.com')(),
      jars.header(pick, 'bilibili.com')(),
      jars.header(pick, 'bilibili.com')(),
    ])
    expect(exports).toBe(1)
    expect(new Set(three).size).toBe(1)
    expect(three[0]).toContain('SESSDATA=')
    // Cached within the TTL, re-exported after it.
    await jars.header(pick, 'bilibili.com')()
    expect(exports).toBe(1)
    clock = COOKIE_TTL_MS + 1
    await jars.header(pick, 'bilibili.com')()
    expect(exports).toBe(2)
    // An export with nothing for the site is not worth caching: the listener
    // is being told to sign in and try again.
    jar = '# Netscape HTTP Cookie File\n'
    clock = 2 * COOKIE_TTL_MS + 2
    expect(await jars.header(pick, 'bilibili.com')()).toBe('')
    expect(exports).toBe(3)
    expect(await jars.header(pick, 'bilibili.com')()).toBe('')
    expect(exports).toBe(4)
    // A hit cached again, then dropped by hand.
    jar = JAR
    await jars.header(pick, 'bilibili.com')()
    expect(exports).toBe(5)
    await jars.header(pick, 'bilibili.com')()
    expect(exports).toBe(5)
    jars.drop()
    await jars.header(pick, 'bilibili.com')()
    expect(exports).toBe(6)
  })
})
